### ISSUE TITLE
个人信息配置页面 UX 失常

### ISSUE THREAD

**Issue by ZoomQuiet** [dockercn/dockercn-issue#5]
# 现象

- 进入 https://docker.cn/Zoom.Quiet/setting
- 进行正当的信息修订, 确定后,所有内容清空
- 再逐一尝试,发现唯一可用的 UX:
    + 每次只修订一项字段
    + 点击 `确定`
    + 点击 `用户中心` 明确数据已更新
    + 回到 [个人设置](https://docker.cn/Zoom.Quiet/setting)
    + 继续以上流程

# 分析

- 太急, 没有对多字段提交进行合理的处理
- 没有前端, 对更新后的状态没有从服务端获取并合理刷新

# 提议

- 招个端 妺纸吧...
- 粮厂米娘 [@张小功犯迷糊](http://weibo.com/n/%E5%BC%A0%E5%B0%8F%E5%8A%9F%E7%8A%AF%E8%BF%B7%E7%B3%8A?from=feed&loc=at) 这样的!

**Comment by chliang2030598** [comment]
设计时候想的不太周全，现在已经修复。
