### ISSUE TITLE
Images push 和删除镜像仓库问题

### ISSUE THREAD

**Issue by wwj718** [dockercn/dockercn-issue#6]
1 docker push 过程因网络问题出现中断之后，再次push会显示 Image xxxxxxxx already pushed, skipping,而实际上其中有些层是不完整的，pull的话会出错

2 打算删了仓库重新push，删除仓库后，再次push，发现依然显示 Image xxxxxxxx already pushed, skipping，是服务器那边没删么

**Comment by chliang2030598** [comment]
服务器之前没有删而是失效，现在服务器会删除镜像

**Comment by wwj718** [comment]
@chliang2030598 好的 感谢回复
